### ISSUE TITLE
assertion failed ... code fragment does not contain the given arm address

### ISSUE THREAD

**Issue by dmeehan1968** [anomalyco/sst#4422]
I have been using 0.0.462 for a while without problems.  Yesterday I decided to upgrade to 0.0.535 and started getting problems with `sst dev` and `sst deploy`.

One part of that was that when running dev or deploy I would intermittently (possibly alternate runs) see a 'log' message (even without verbose mode) which mentioned the error in the title of this issue.

I downgraded to 0.0.462 and the issue persisted.  I assume that its coming from a dependency that gets installed when `sst install` runs after the upgrade/downgrade.

It appears to affect all sst commands that touch the cloud, so `refresh` is also affected.

When this log message appears, the command then halts indefinitely (no further output however long I wait).

Ctrl-C to abort and then running again often then succeeds, although `sst deploy` seems to fail every time, whereas `sst dev` will succeed (on alternate invocations).

```
time=2024-07-17T08:27:03.003+01:00 level=INFO msg=publishing type=*project.StackEvent
time=2024-07-17T08:27:03.003+01:00 level=INFO msg=publishing type=*project.StackEvent
time=2024-07-17T08:27:03.033+01:00 level=INFO msg=publishing type=*project.StackEvent
time=2024-07-17T08:27:03.034+01:00 level=INFO msg=publishing type=*project.StackEvent
time=2024-07-17T08:27:03.284+01:00 level=INFO msg=publishing type=*project.StackEvent                                                                                                                      
time=2024-07-17T08:27:03.285+01:00 level=INFO msg=publishing type=*project.StackEvent
|  Log         assertion failed [arm_interval().contains(address)]: code fragment does not contain the given arm address
|  Log         (CodeFragmentMetadata.cpp:48 instruction_extents_for_arm_address)
⠏  Deploying   [3 skipped]       
```

**Comment by dnutsh** [comment]
`GODEBUG=asyncpreemptoff=1 sst refresh --stage production --verbose` worked for me. I'm running `sst 3.4.27` on a M1 mac.

**Comment by richaquino** [comment]
I had a similar issue.

When I installed sst...
`npm i sst
sst install`
... I kept seeing that running pulumi processes were Intel.

I also saw Intel when looking at running pulumi processes in activity monitor like @dmeehan1968 did above.  (I have a "Kind" column, don't remember if I added that somehow).

I'd go through a few rounds of deleting them (double clicking on the process in activity monitor tells you where they are), but every time I'd reinstallthey'd still come back running as Intel, not "apple" or arm.

When I ran
`npx which sst`
it would return 
`node_modules/.bin/sst`

I looked at that file, and saw this line (constructing the file to execute)
`const name = sst-${process.platform}-${process.arch}`


So I ran this command to figure out what node thought process.platform and process.arch were...
`node -e 'console.log(process.platform, process.arch)'`

It returned
`darwin x64`

Thinking "wtf?  x64?", I ran this command because I thought maybe I was nuts and my laptop wasn't apple silicon
`arch`
It returns
`arm64`

Going back to that line from node_modules/.bin/sst, I found this folder
`node_modules/sst-darwin-x64`
and it dawned on me.

Somehow my version of node was Intel.  It turned out I had an old version of node installed globally.  I think it was around from an old intel based laptop.  When I bought this new macbook pro, I ported everything over from the old laptop.  That included an intel version of node.

So, I deleted that version of node, that I found with this command
`which node`
And reinstalled node (arm this time) with n

I then re-deleted all the sst and pulumi binaries I could find.  Then reran 
`npm i sst
sst install`

And now I had 
`node_modules/sst-darwin-arm64`
When I ran sst dev and checked activity monitor, I starting seeing "Apple" next to the pulumi processes.

My world was right as rain again.

So, my guess is that pinning to 6.41.0 for @emlegweak helps because that's an Arm/Apple version of the plugin, while new ones are coming in as Intel because of the version of Node. 

Running this command from terminal should help...
`arch && node -e 'console.log(process.arch)'`

If you don't see `arm64` on two lines (first line being OS/container architecture, second being node's), then it's definitely your problem.
