### ISSUE TITLE
Console: Issue with API Gateway state management

### ISSUE THREAD

**Issue by nguyendon** [anomalyco/sst#5031]
I am deploying with Console and on both my dev and prod stages I am getting errors for an "already exists for this API" error. This route has only ever been created with SST and deployed with Console. 

```
   NaasAPIRouteXuckha sst:aws:ApiGatewayV2LambdaRoute → NaasAPIRouteXuckhaRoute aws:apigatewayv2:Route
     sdk-v2/provider2.go:520: sdk.helper_schema: creating API Gateway v2 Route: operation error ApiGatewayV2: CreateRoute, https response error StatusCode: 409, RequestID: 4eff70f4-19f3-4fb2-ba36-d9748ffc6b70, ConflictException: Route with key ANY /{proxy+} already exists for this API: provider=aws@6.57.0
   NaasAPIRouteXuckha sst:aws:ApiGatewayV2LambdaRoute → NaasAPIRouteXuckhaRoute aws:apigatewayv2:Route
   Route: operation error ApiGatewayV2: CreateRoute, https response error StatusCode: 409, RequestID: 4eff70f4-19f3-4fb2-ba36-d9748ffc6b70, ConflictException: Route with key ANY /{proxy+} already exists for this API
```

**Comment by AllyMurray** [comment]
Similar issue with ApiGatewayV1:

```
   api sst:aws:ApiGatewayV1 → apiResourceTuwecr aws:apigateway:Resource
     sdk-v2/provider2.go:520: sdk.helper_schema: creating API Gateway Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: 54306eae-62b5-4b48-bf2d-70ac06a8f987, ConflictException: Another resource with the same parent already has this name: {proxy+}: provider=aws@6.57.0

   api sst:aws:ApiGatewayV1 → apiResourceTuwecr aws:apigateway:Resource
   Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: 54306eae-62b5-4b48-bf2d-70ac06a8f987, ConflictException: Another resource with the same parent already has this name: {proxy+}
```

**Comment by nguyendon** [comment]
This is a pretty serious issue for us as we cannot deploy anything. I think it would be for others as well.

Cc: @fwang @jayair

**Comment by AllyMurray** [comment]
I have managed to deploy but it involved updating the state in S3. The resource has a suffix added to it, the suffix is a hash made up of the path and the api id. I saw in the components file there was an issue with api id because it was of type output, I don't know if this has been accidentally fixed but the hash has definitely changed.

I tried to deploy to get the new suffix and then did a find and replace in the state that's stored in S3.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/82f8d49f-f44f-49c6-96a8-8ebeffab79ca">
<img width="2087" alt="image" src="https://github.com/user-attachments/assets/545f37b0-f054-4fe3-aadc-4e7b33725572">

**Comment by nguyendon** [comment]
Thanks for the tip @AllyMurray, I'll give that a shot. 

Unfortunately we have many deploys of the same app so manually fixing the state would be difficult for each instance but I'll try this out on one of our dev instances.

**Comment by jayair** [comment]
@nguyendon can you share a snippet of the API definition in your case?

**Comment by fwang** [comment]
@nguyendon yeah can you share ur `new sst.aws.ApiGatewayV2` definition and the routes. Also, which version did u upgrade from/to?

**Comment by nguyendon** [comment]
@jayair @fwang 

```
export const api = new sst.aws.ApiGatewayV2('Api', {
  accessLog: {
    retention: '1 month',
  },
  cors: false,
  transform: {
    route: {
      handler:  {
        memory: '1024 MB',
        architecture: 'arm64',
        runtime: 'nodejs20.x',
        live: false,
        vpc: {
          securityGroups: vpc.vpcSecurityGroups,
          privateSubnets: vpc.privateSubnets,
        }
      },
    },
  },
});

api.route('ANY /{proxy+}', 'packages/functions/src/api.handler');
```

We've been on `3.1.7` for a couple of months, the deploys just stopped working for us when we last tried to deploy about 3 weeks ago. The previous deploy that was successful before that was 2 months ago. I upgraded to `3.3.13` locally and am still seeing this. 

This is the link to the deploy log if you have access to it: https://console.sst.dev/libum/naas/autodeploy/gk6ontqsp1gmccqtil6veufx

**Comment by nguyendon** [comment]
Actually `3.1.7` works locally for me atm but fails when autodeploying with console. I haven't had the chance to bisect which release started failing but can maybe try that out when I get the chance.

**Comment by fwang** [comment]
@nguyendon Thanks for the details!

Yeah the issue is what @AllyMurray pointed out. There was a bug in earlier versions of SST where the route id was not generated deterministically.

To get around the issue, in your specific case, change the route from `ANY /{proxy+}` to `$default`. `$default` is another way to define a catch all route in API Gateway v2. The behavior should remain the same.

Feel free to reopen the issue if this doesn't work for you.

**Comment by nguyendon** [comment]
@fwang that worked, thanks!

**Comment by nguyendon** [comment]
I ran into another issue but i looks like I can't reopen this issue. It's related to identifying the actual API GW: https://github.com/sst/sst/issues/5059
