### ISSUE TITLE
Support docker based (Image) functions (via aws-lambda-adapter)

### ISSUE THREAD

**Issue by rracariu** [anomalyco/sst#5084]
Currently functions can be defined using Node APIs or whatever programming language Lambada Runtime there available for it.

For a multitude of factors, supporting a docker based type of function, by using the `aws-lambda-adapter` would make life simpler overall for projects that don't fit this pattern.

**Comment by aeftimia** [comment]
I've been waiting for that too. SST v3 only officially supports using containers for servers. They have a [note in their migration guide](https://sst.dev/docs/migrate-from-v2) that lambdas with other runtimes are on the roadmap with a few issues linked. Despite now being v`N-1`, I've found [SST v2](https://v2.sst.dev/) to still be a great option get local lambda debugging across runtimes with integration with launching your entire front and backend. It's been [3 months](https://sst.dev/blog/sst-v3/) since they launched v3, so I'm still hopeful we'll see the gap in features close within the next few months. 

Having switched between v2 and v3 a few times now, I can attest the migration process has been pretty simple.

**Comment by jayair** [comment]
Yeah container runtime for Lambda is on the short term roadmap. Closing in favour of this: https://github.com/sst/sst/issues/4462
